Simple Linear Regression

##Importing The libraries

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [16]:
df=pd.read_csv('income_data.csv')
df

YearsExperience  Income
0               1.1   39343
1               1.3   46205
2               1.5   37731
3               2.0   43525
4               2.2   39891
5               2.9   56642
6               3.0   60150
7               3.2   54445
8               3.2   64445
9               3.7   57189
10              3.9   63218
11              4.0   55794
12              4.0   56957
13              4.1   57081
14              4.5   61111
15              4.9   67938
16              5.1   66029
17              5.3   83088
18              5.9   81363
19              6.0   93940
20              6.8   91738
21              7.1   98273
22              7.9  101302
23              8.2  113812
24              8.7  109431
25              9.0  105582
26              9.5  116969
27              9.6  112635
28             10.3  122391
29             10.5  121872

In [17]:
x=df[['Income']]
x

Income
0    39343
1    46205
2    37731
3    43525
4    39891
5    56642
6    60150
7    54445
8    64445
9    57189
10   63218
11   55794
12   56957
13   57081
14   61111
15   67938
16   66029
17   83088
18   81363
19   93940
20   91738
21   98273
22  101302
23  113812
24  109431
25  105582
26  116969
27  112635
28  122391
29  121872

Creating a matrix for dataset

In [48]:
x=df.iloc[ 0:7,0:2 ].values
x

array([[1.1000e+00, 3.9343e+04],
       [1.3000e+00, 4.6205e+04],
       [1.5000e+00, 3.7731e+04],
       [2.0000e+00, 4.3525e+04],
       [2.2000e+00, 3.9891e+04],
       [2.9000e+00, 5.6642e+04],
       [3.0000e+00, 6.0150e+04]])

In [49]:
x=df.iloc[ 0:7,0:2 ]
x

YearsExperience  Income
0              1.1   39343
1              1.3   46205
2              1.5   37731
3              2.0   43525
4              2.2   39891
5              2.9   56642
6              3.0   60150

In [50]:
X = df.iloc[ : , 0:-1 ].values
print(X)

[[ 1.1]
 [ 1.3]
 [ 1.5]
 [ 2. ]
 [ 2.2]
 [ 2.9]
 [ 3. ]
 [ 3.2]
 [ 3.2]
 [ 3.7]
 [ 3.9]
 [ 4. ]
 [ 4. ]
 [ 4.1]
 [ 4.5]
 [ 4.9]
 [ 5.1]
 [ 5.3]
 [ 5.9]
 [ 6. ]
 [ 6.8]
 [ 7.1]
 [ 7.9]
 [ 8.2]
 [ 8.7]
 [ 9. ]
 [ 9.5]
 [ 9.6]
 [10.3]
 [10.5]]


Creating a vector for depandent variable

In [51]:
y=df.iloc[ :, -1 ].values
y    

array([ 39343,  46205,  37731,  43525,  39891,  56642,  60150,  54445,
        64445,  57189,  63218,  55794,  56957,  57081,  61111,  67938,
        66029,  83088,  81363,  93940,  91738,  98273, 101302, 113812,
       109431, 105582, 116969, 112635, 122391, 121872], dtype=int64)

Spliting the dataset into training set and test set

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
from pandas.core.common import random_state
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [59]:
print(X_train)

[[ 9.6]
 [ 4. ]
 [ 5.3]
 [ 7.9]
 [ 2.9]
 [ 5.1]
 [ 3.2]
 [ 4.5]
 [ 8.2]
 [ 6.8]
 [ 1.3]
 [10.5]
 [ 3. ]
 [ 2.2]
 [ 5.9]
 [ 6. ]
 [ 3.7]
 [ 3.2]
 [ 9. ]
 [ 2. ]
 [ 1.1]
 [ 7.1]
 [ 4.9]
 [ 4. ]]


In [60]:
print(y_train)

[112635  55794  83088 101302  56642  66029  64445  61111 113812  91738
  46205 121872  60150  39891  81363  93940  57189  54445 105582  43525
  39343  98273  67938  56957]


In [69]:
y_train=y_train.reshape(-1,1)
print(y_train)

[[112635]
 [ 55794]
 [ 83088]
 [101302]
 [ 56642]
 [ 66029]
 [ 64445]
 [ 61111]
 [113812]
 [ 91738]
 [ 46205]
 [121872]
 [ 60150]
 [ 39891]
 [ 81363]
 [ 93940]
 [ 57189]
 [ 54445]
 [105582]
 [ 43525]
 [ 39343]
 [ 98273]
 [ 67938]
 [ 56957]]


In [72]:
Training_set= np.concatenate((X_train,y_train),1)

In [73]:
Training_set

array([[9.60000e+00, 1.12635e+05],
       [4.00000e+00, 5.57940e+04],
       [5.30000e+00, 8.30880e+04],
       [7.90000e+00, 1.01302e+05],
       [2.90000e+00, 5.66420e+04],
       [5.10000e+00, 6.60290e+04],
       [3.20000e+00, 6.44450e+04],
       [4.50000e+00, 6.11110e+04],
       [8.20000e+00, 1.13812e+05],
       [6.80000e+00, 9.17380e+04],
       [1.30000e+00, 4.62050e+04],
       [1.05000e+01, 1.21872e+05],
       [3.00000e+00, 6.01500e+04],
       [2.20000e+00, 3.98910e+04],
       [5.90000e+00, 8.13630e+04],
       [6.00000e+00, 9.39400e+04],
       [3.70000e+00, 5.71890e+04],
       [3.20000e+00, 5.44450e+04],
       [9.00000e+00, 1.05582e+05],
       [2.00000e+00, 4.35250e+04],
       [1.10000e+00, 3.93430e+04],
       [7.10000e+00, 9.82730e+04],
       [4.90000e+00, 6.79380e+04],
       [4.00000e+00, 5.69570e+04]])

In [61]:
print(X_test)

[[ 1.5]
 [10.3]
 [ 4.1]
 [ 3.9]
 [ 9.5]
 [ 8.7]]


In [62]:
print(y_test)

[ 37731 122391  57081  63218 116969 109431]


In [76]:
y_test=y_test.reshape(-1,1)
y_test

array([[ 37731],
       [122391],
       [ 57081],
       [ 63218],
       [116969],
       [109431]], dtype=int64)

In [78]:
Testing_set= np.concatenate((X_test,y_test),1)
Testing_set

array([[1.50000e+00, 3.77310e+04],
       [1.03000e+01, 1.22391e+05],
       [4.10000e+00, 5.70810e+04],
       [3.90000e+00, 6.32180e+04],
       [9.50000e+00, 1.16969e+05],
       [8.70000e+00, 1.09431e+05]])