In [6]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
# Importing the dataset
dataset = pd.read_csv("Startups.csv")
X = dataset.iloc[ : , 0:-1 ].values
y = dataset.iloc[ : , -1 ].values

In [8]:
print(X)

[[165349.2 'Large' 136897.8 471784.1 'New York']
 [162597.7 'Small' 151377.59 443898.53 'California']
 [153441.51 'Very Large' 101145.55 407934.54 'Florida']
 [144372.41 'Very Small' 118671.85 383199.62 'New York']
 [142107.34 'Small' 91391.77 366168.42 'Florida']
 [131876.9 'Very Large' 99814.71 362861.36 'New York']
 [134615.46 'Very Small' 147198.87 127716.82 'California']
 [130298.13 'Large' 145530.06 323876.68 'Florida']
 [120542.52 'Small' 148718.95 311613.29 'New York']
 [123334.88 'Very Large' 108679.17 304981.62 'California']
 [101913.08 'Very Small' 110594.11 229160.95 'Florida']
 [100671.96 'Small' 91790.61 249744.55 'California']
 [93863.75 'Very Large' 127320.38 249839.44 'Florida']
 [91992.39 'Very Small' 135495.07 252664.93 'California']
 [119943.24 'Large' 156547.42 256512.92 'Florida']]


In [9]:
# Encoding the categorical variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('Encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [10]:
print(X)

[[1.0 0.0 0.0 0.0 165349.2 136897.8 471784.1 'New York']
 [0.0 1.0 0.0 0.0 162597.7 151377.59 443898.53 'California']
 [0.0 0.0 1.0 0.0 153441.51 101145.55 407934.54 'Florida']
 [0.0 0.0 0.0 1.0 144372.41 118671.85 383199.62 'New York']
 [0.0 1.0 0.0 0.0 142107.34 91391.77 366168.42 'Florida']
 [0.0 0.0 1.0 0.0 131876.9 99814.71 362861.36 'New York']
 [0.0 0.0 0.0 1.0 134615.46 147198.87 127716.82 'California']
 [1.0 0.0 0.0 0.0 130298.13 145530.06 323876.68 'Florida']
 [0.0 1.0 0.0 0.0 120542.52 148718.95 311613.29 'New York']
 [0.0 0.0 1.0 0.0 123334.88 108679.17 304981.62 'California']
 [0.0 0.0 0.0 1.0 101913.08 110594.11 229160.95 'Florida']
 [0.0 1.0 0.0 0.0 100671.96 91790.61 249744.55 'California']
 [0.0 0.0 1.0 0.0 93863.75 127320.38 249839.44 'Florida']
 [0.0 0.0 0.0 1.0 91992.39 135495.07 252664.93 'California']
 [1.0 0.0 0.0 0.0 119943.24 156547.42 256512.92 'Florida']]


In [11]:
# Encoding the categorical variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('Encoder', OneHotEncoder(), [7])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [12]:
print(X)

[[0.0 0.0 1.0 1.0 0.0 0.0 0.0 165349.2 136897.8 471784.1]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 162597.7 151377.59 443898.53]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 153441.51 101145.55 407934.54]
 [0.0 0.0 1.0 0.0 0.0 0.0 1.0 144372.41 118671.85 383199.62]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 142107.34 91391.77 366168.42]
 [0.0 0.0 1.0 0.0 0.0 1.0 0.0 131876.9 99814.71 362861.36]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 134615.46 147198.87 127716.82]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.0 130298.13 145530.06 323876.68]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 120542.52 148718.95 311613.29]
 [1.0 0.0 0.0 0.0 0.0 1.0 0.0 123334.88 108679.17 304981.62]
 [0.0 1.0 0.0 0.0 0.0 0.0 1.0 101913.08 110594.11 229160.95]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 100671.96 91790.61 249744.55]
 [0.0 1.0 0.0 0.0 0.0 1.0 0.0 93863.75 127320.38 249839.44]
 [1.0 0.0 0.0 0.0 0.0 0.0 1.0 91992.39 135495.07 252664.93]
 [0.0 1.0 0.0 1.0 0.0 0.0 0.0 119943.24 156547.42 256512.92]]
